# Site Settings
title: Manju & Krishna
email: krishna.teja300@gmail.com
description: >
  Wedding Information Website
baseurl: ""
url: "http://localhost:4000"
github_username:  krish300
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM